# Generated by Django 5.2.3 on 2025-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad_user",
            name="rid",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
