# Generated by Django 5.2.5 on 2025-09-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0002_ad_user_rid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Knowledgebase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "knowledgebase",
                "verbose_name_plural": "knowledgebase",
                "db_table": "knowledgebase",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_knowledgebase.name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="knowledgebase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categorys",
                to="cybsmodels.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="compliance",
            name="knowledgebase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliances",
                to="cybsmodels.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="control_definition",
            name="knowledgebase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_definitions",
                to="cybsmodels.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="control_definition_translation",
            name="knowledgebase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_definition_translations",
                to="cybsmodels.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="knowledgebase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="cybsmodels.knowledgebase",
            ),
        ),
    ]
