# Generated by Django 5.2.5 on 2025-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0003_knowledgebase_category_knowledgebase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="knowledgebase_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compliance",
            name="knowledgebase_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="control_definition",
            name="knowledgebase_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="control_definition_translation",
            name="knowledgebase_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="knowledgebase_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
