# Generated by Django 5.2.5 on 2025-09-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0004_category_knowledgebase_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="knowledgebase_path",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="knowledgebase_path",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="control_definition",
            name="knowledgebase_path",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="control_definition_translation",
            name="knowledgebase_path",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="knowledgebase_path",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
