# Generated by Django 5.2.5 on 2025-09-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0005_alter_category_knowledgebase_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="knowledgebase_path",
            field=models.TextField(db_index=True, default="category"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="knowledgebase_path",
            field=models.TextField(db_index=True, default="compliance"),
        ),
        migrations.AlterField(
            model_name="control_definition",
            name="knowledgebase_path",
            field=models.TextField(db_index=True, default="control_definition"),
        ),
        migrations.AlterField(
            model_name="control_definition_translation",
            name="knowledgebase_path",
            field=models.TextField(
                db_index=True, default="control_definition_translation"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="knowledgebase_path",
            field=models.TextField(db_index=True, default="tag"),
        ),
    ]
