# Generated by Django 5.2.5 on 2025-10-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0006_alter_category_knowledgebase_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.TextField(db_index=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "hosts",
                    models.ManyToManyField(
                        blank=True, related_name="networks", to="cybsmodels.host"
                    ),
                ),
            ],
            options={
                "verbose_name": "network",
                "verbose_name_plural": "network",
                "db_table": "network",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("network",), name="unique_network.network"
                    )
                ],
            },
        ),
    ]
