# Generated by Django 5.2.5 on 2025-10-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0007_network"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostname",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True)),
            ],
            options={
                "verbose_name": "hostname",
                "verbose_name_plural": "hostname",
                "db_table": "hostname",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_hostname.name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Host_Update",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_id", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("security", "security"),
                            ("feature", "feature"),
                            ("unkown", "unkown"),
                        ],
                        default="unknown",
                    ),
                ),
                ("installed_by", models.TextField(blank=True, null=True)),
                ("installed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_updates",
                        to="cybsmodels.hostname",
                    ),
                ),
            ],
            options={
                "verbose_name": "host_update",
                "verbose_name_plural": "host_update",
                "db_table": "host_update",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host",), name="unique_host_update.host"
                    )
                ],
            },
        ),
    ]
