# Generated by Django 5.2.5 on 2025-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0008_hostname_host_update"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="host_update",
            name="unique_host_update.host",
        ),
        migrations.AddConstraint(
            model_name="host_update",
            constraint=models.UniqueConstraint(
                fields=("host", "update_id", "installed_on", "type"),
                name="unique_host_update.host_update_id_installed_on_type",
            ),
        ),
    ]
