# Generated by Django 5.2.5 on 2025-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0009_remove_host_update_unique_host_update_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host_update",
            name="installed_on",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="host_update",
            name="type",
            field=models.TextField(
                choices=[
                    ("security", "security"),
                    ("feature", "feature"),
                    ("unkown", "unkown"),
                ],
                db_index=True,
                default="unknown",
            ),
        ),
    ]
