# Generated by Django 5.2.5 on 2025-10-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0010_alter_host_update_installed_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostname",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("windows", "windows"),
                    ("linux", "linux"),
                    ("mac", "mac"),
                    ("other", "other"),
                ],
                null=True,
            ),
        ),
    ]
