# Generated by Django 5.2.5 on 2025-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0011_hostname_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostname",
            name="install_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
