# Generated by Django 5.2.5 on 2025-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0012_hostname_install_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="control",
            name="status",
            field=models.TextField(
                choices=[
                    ("ok", "ok"),
                    ("ko", "ko"),
                    ("not_applicable", "not_applicable"),
                    ("not_started", "not_started"),
                    ("in_progress", "in_progress"),
                    ("manual", "manual"),
                    ("unknown", "unknown"),
                ],
                db_index=True,
                default="not_started",
            ),
        ),
    ]
