# Generated by Django 5.2.5 on 2025-10-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0013_alter_control_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="installed_software",
            name="unique_installed_software.host_software",
        ),
        migrations.AlterField(
            model_name="installed_software",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installed_softwares",
                to="cybsmodels.hostname",
            ),
        ),
        migrations.AlterField(
            model_name="installed_software",
            name="version",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="installed_software",
            constraint=models.UniqueConstraint(
                fields=("host", "software", "version"),
                name="unique_installed_software.host_software_version",
            ),
        ),
    ]
