# Generated by Django 5.2.5 on 2025-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cybsmodels",
            "0014_remove_installed_software_unique_installed_software_host_software_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="installed_software",
            name="unique_installed_software.host_software_version",
        ),
        migrations.RenameField(
            model_name="installed_software",
            old_name="software",
            new_name="name",
        ),
        migrations.AddConstraint(
            model_name="installed_software",
            constraint=models.UniqueConstraint(
                fields=("host", "name", "version"),
                name="unique_installed_software.host_name_version",
            ),
        ),
    ]
