# Generated by Django 5.2.5 on 2025-10-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cybsmodels",
            "0015_remove_installed_software_unique_installed_software_host_software_version_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Installed_Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True)),
                ("version", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_applications",
                        to="cybsmodels.hostname",
                    ),
                ),
            ],
            options={
                "verbose_name": "installed_application",
                "verbose_name_plural": "installed_application",
                "db_table": "installed_application",
            },
        ),
        migrations.DeleteModel(
            name="Installed_Software",
        ),
        migrations.AddConstraint(
            model_name="installed_application",
            constraint=models.UniqueConstraint(
                fields=("host", "name", "version"),
                name="unique_installed_application.host_name_version",
            ),
        ),
    ]
