# Generated by Django 5.2.5 on 2025-10-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0016_installed_application_delete_installed_software_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windows_user",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="windows_users",
                to="cybsmodels.host",
            ),
        ),
    ]
