# Generated by Django 5.2.5 on 2025-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0017_alter_windows_user_host"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="windows_user",
            name="unique_windows_user.user_host",
        ),
        migrations.RenameField(
            model_name="windows_user",
            old_name="user",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="windows_user",
            old_name="PswdRequired",
            new_name="password_required",
        ),
        migrations.RemoveField(
            model_name="windows_user",
            name="AcctDisabled",
        ),
        migrations.RemoveField(
            model_name="windows_user",
            name="PswdCanBeChanged",
        ),
        migrations.RemoveField(
            model_name="windows_user",
            name="PswdExpires",
        ),
        migrations.RemoveField(
            model_name="windows_user",
            name="PswdExpiresTime",
        ),
        migrations.RemoveField(
            model_name="windows_user",
            name="PswdLastSetTime",
        ),
        migrations.AddField(
            model_name="windows_user",
            name="account_expires",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="full_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="last_logon",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="password_changeable_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="password_expires",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="password_last_set",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="windows_user",
            name="user_may_change_password",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="windows_user",
            constraint=models.UniqueConstraint(
                fields=("name", "host"), name="unique_windows_user.name_host"
            ),
        ),
    ]
