# Generated by Django 5.2.5 on 2025-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cybsmodels",
            "0018_remove_windows_user_unique_windows_user_user_host_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="visible_from",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="cybsmodels.network"
            ),
        ),
    ]
