# Generated by Django 5.2.5 on 2025-10-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0019_service_visible_from"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="network",
            name="unique_network.network",
        ),
        migrations.AddField(
            model_name="network",
            name="name",
            field=models.TextField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="network",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_network.name"
            ),
        ),
    ]
