# Generated by Django 5.2.5 on 2025-10-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cybsmodels",
            "0020_remove_network_unique_network_network_network_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="visible_from",
            field=models.ManyToManyField(
                blank=True, related_name="hosts", to="cybsmodels.network"
            ),
        ),
    ]
