# Generated by Django 5.2.5 on 2025-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0021_host_visible_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="visible_from",
            field=models.ManyToManyField(
                blank=True, related_name="visible_hosts", to="cybsmodels.network"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="visible_from",
            field=models.ManyToManyField(
                blank=True, related_name="visible_services", to="cybsmodels.network"
            ),
        ),
    ]
