# Generated by Django 5.2.1 on 2025-10-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0022_alter_host_visible_from_alter_service_visible_from"),
    ]

    operations = [
        migrations.RenameField(
            model_name="host",
            old_name="visible_from",
            new_name="visible_from_networks",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="visible_from",
            new_name="visible_from_networks",
        ),
    ]
